services:
   postgres:
     container_name: ms_pg_sql
     image: postgres
     environment:
       POSTGRES_USER: felix
       POSTGRES_PASSWORD: 7991@felix
       PGDATA: /var/lib/postgresql/data
     volumes:
       - postgres/var/lib/postgresql/data
     ports:
       - 5432:5432
     networks:
       - microservices-network
     restart: unless-stopped
   pgadmin:
     container_name: ms_pgadmin
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
       PGADMIN_CONFIG_SERVER_MODE: 'False'
     volumes:
        - pgadmin:/var/lib/pgadmin
     ports:
           - "5050:80"
     networks:
       - microservices-net
     restart: unless-stopped
   mongodb:
     image: mongo
     container_name: mongo_db
     ports:
       - 27017:27017
     volumes:
       - mongo:/data
     environment:
       - MONGO_INITDB_ROOT_USERNAME=felix
       - MONGO_INITDB_ROOT_PASSWORD=7991@feliX

   mongo-express:
     image: mongo-express
     container_name: mongo_express
     restart: always
     ports:
       - 8081:8081
     environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=felix
       - ME_CONFIG_MONGODB_ADMINPASSWORD=7991@feliX
       - ME_CONFIG_MONGODB_SERVER=mongodb
   networks:
     microservices-network:
       driver: bridge
   volumes:
     postgres:
     pgadmin:
     mongo: