services:
   postgres:
     container_name: ms_pg_sql
     image: postgres
     environment:
       POSTGRES_USER: felix
       POSTGRES_PASSWORD: 7991@felix
       PGDATA: /var/lib/postgresql/data
     volumes:
       - postgres/var/lib/postgresql/data
     ports:
       - 5432:5432
     networks:
       - microservices-network
     restart: unless-stopped
   pgadmin:
     container_name: ms_pgadmin
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
       PGADMIN_CONFIG_SERVER_MODE: 'False'
     volumes:
        - pgadmin:/var/lib/pgadmin
     ports:
           - "5050:80"
     networks:
       - microservices-net
     restart: unless-stopped

   networks:
     microservices-network:
       driver: bridge
   volumes:
     postgres:
     pgadmin:
     mongo: