spring:
  data:
    mongodb:
      username: ms_reference
      password: ms_ref@rence
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 9090
