server:
  port: 8090
spring:
  data:
    mongodb:
      username: felix
      password: 7991@feliX
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin